package com.zw.req;



public class EbookQueryReq extends PageReq{

    private Long id;

    private String name;


    private Long category1Id;


    private Long category2Id;




    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }


    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.name
     *
     * @param name the value for ebook.name
     *
     * @mbg.generated Fri Dec 03 14:11:28 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.category1_id
     *
     * @return the value of ebook.category1_id
     *
     * @mbg.generated Fri Dec 03 14:11:28 CST 2021
     */
    public Long getCategory1Id() {
        return category1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.category1_id
     *
     * @param category1Id the value for ebook.category1_id
     *
     * @mbg.generated Fri Dec 03 14:11:28 CST 2021
     */
    public void setCategory1Id(Long category1Id) {
        this.category1Id = category1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.category2_id
     *
     * @return the value of ebook.category2_id
     *
     * @mbg.generated Fri Dec 03 14:11:28 CST 2021
     */
    public Long getCategory2Id() {
        return category2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.category2_id
     *
     * @param category2Id the value for ebook.category2_id
     *
     * @mbg.generated Fri Dec 03 14:11:28 CST 2021
     */
    public void setCategory2Id(Long category2Id) {
        this.category2Id = category2Id;
    }

}