package com.zw.domain;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.id
     *
     * @mbg.generated Sat Dec 04 19:19:07 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.content
     *
     * @mbg.generated Sat Dec 04 19:19:07 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.id
     *
     * @return the value of content.id
     *
     * @mbg.generated Sat Dec 04 19:19:07 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.id
     *
     * @param id the value for content.id
     *
     * @mbg.generated Sat Dec 04 19:19:07 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.content
     *
     * @return the value of content.content
     *
     * @mbg.generated Sat Dec 04 19:19:07 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.content
     *
     * @param content the value for content.content
     *
     * @mbg.generated Sat Dec 04 19:19:07 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }
}