package com.zw.mapper;

import com.zw.domain.Doc;
import com.zw.domain.DocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    long countByExample(DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int deleteByExample(DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int insert(Doc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int insertSelective(Doc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    List<Doc> selectByExample(DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    Doc selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int updateByExampleSelective(@Param("record") Doc record, @Param("example") DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int updateByExample(@Param("record") Doc record, @Param("example") DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int updateByPrimaryKeySelective(Doc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated Sat Dec 04 18:43:04 CST 2021
     */
    int updateByPrimaryKey(Doc record);
}