package com.zw.mapper;

import com.zw.domain.EbookSnapshot;
import com.zw.domain.EbookSnapshotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EbookSnapshotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    long countByExample(EbookSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int deleteByExample(EbookSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int insert(EbookSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int insertSelective(EbookSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    List<EbookSnapshot> selectByExample(EbookSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    EbookSnapshot selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") EbookSnapshot record, @Param("example") EbookSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int updateByExample(@Param("record") EbookSnapshot record, @Param("example") EbookSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int updateByPrimaryKeySelective(EbookSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook_snapshot
     *
     * @mbg.generated Fri Dec 03 14:10:53 CST 2021
     */
    int updateByPrimaryKey(EbookSnapshot record);
}